FROM python:3.7.2-alpine

# Install deps
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# Change work dir
WORKDIR /usr/src/app

# Pip install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# Add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# Copy app to container.
COPY . /usr/src/app

# Start Flask
CMD ["/usr/src/app/entrypoint-prod.sh"]
