# BUILDER
FROM node:11.12.0-alpine as builder 

# Set working dir
WORKDIR /usr/src/app

# Install app deps
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json 
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci
RUN npm install react-scripts@2.1.8 -g --silent

# Set env vars
ARG REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV 
ENV NOVE_ENV $NODE_ENV 

# Create build 
COPY . /usr/src/app 
RUN npm run build 

# PROD Deploy
FROM nginx:1.15.9-alpine 

# Copy static files
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# Expose port
EXPOSE 80

# Run Nginx 
CMD ["nginx", "-g", "daemon off;"]